### ISSUE TITLE
AntBasedAndroidApplication won't build on Windows

### ISSUE THREAD

**Issue by xverges** [robospock/RoboSpock#13]
Building `AntBasedAndroidApplication` fails to lauch `android` and `ant`. If I modify the commandLine value it works (but obviously breaks on non-Windows) 

```
-    commandLine 'android', 'update', 'project', '-p', '.'
+    commandLine 'cmd', '/c', 'android', 'update', 'project', '-p', '.'
```

and

```
-    commandLine 'ant', 'debug'
+    commandLine 'cmd', '/c', 'ant', 'debug'
```

Unfortunately, I don't know if there is a gradle idiom to handle platform dependent variables, so I cannot supply a fix http://stackoverflow.com/questions/11235614/how-to-detect-the-current-os-from-gradle

**Comment by pjakubczyk** [comment]
I don't plan to support ANT since Google completely switched to Gradle.
