### ISSUE TITLE
FYI: New robospock plugin for Gradle

### ISSUE THREAD

**Issue by Centril** [robospock/RoboSpock#28]
# For your information:

I've created a new Gradle plugin for robospock which actually works and makes life ridiculously simple...
Here it is: **https://github.com/Centril/gradle-plugin-robospock**

You can apply it in a host of different ways, but the most simple is:

``` groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'se.centril.robospock:gradle-plugin-robospock:0.2.0'
    }
}

['android-sdk-manager', 'com.android.application', 'robospock']
    .each { apply plugin: it }

android {
    buildTypes {
        defaultConfig {
            minSdkVersion 9
            targetSdkVersion 20
        }
    }
    compileSdkVersion 20
    buildToolsVersion "20"

    // more exciting stuff...
}
```

Then you can put all your testing classes in **`{android-project-root}/src/test/`**.
Thats it =)

**Comment by pjakubczyk** [comment]
I think it's not valid since google add support to their official plugin
