### ISSUE TITLE
Robolectric 3.0 support

### ISSUE THREAD

**Issue by safwankamarrudin** [robospock/RoboSpock#33]
Are there any plans to upgrade Robolectric to 3.0?

**Comment by wojtekerbetowski** [comment]
I don't think anyone at this moment is working on it. I doubt it will
happen very soon, but it's definitely worth of doing.

**Comment by pjakubczyk** [comment]
Actually I started the work few days ago. It's available in this branch
https://github.com/Polidea/RoboSpock/tree/robolectric3

However I would like to release an update with Robolectric 3 because it's still a snapshot version.

**Comment by safwankamarrudin** [comment]
@pjakubczyk That's awesome! I'll keep an eye on this thread for updates.

**Comment by jaredsburrows** [comment]
@pjakubczyk  How is this coming along?

**Comment by walid-halabi-myob** [comment]
+1

**Comment by kdawgwilk** [comment]
+1

**Comment by pjakubczyk** [comment]
There is support for 2.4 for this moment. I wanted to skip the version but the leap was to big.

**Comment by pjakubczyk** [comment]
Issue moved to
https://github.com/robospock/RoboSpock/issues/1

cc @kdawgwilk @safwankamarrudin @jaredsburrows @walid-halabi-myob

**Comment by pjakubczyk** [comment]
Support for Robolectric 3.0 is about to be done. In few days it will be published. For now you can check if works with your project using jitpack
https://jitpack.io/#robospock/RoboSpock/c9ee6221cd9ac5010bb8c39e110b7e9c272e0a9a

Please mind the fact that groovy version is higher  so there might be some compilation errors.

**Comment by pjakubczyk** [comment]
0.7 support Robolectric 3.0
you can use testCompile 'org.robospock:robospock:0.7.0'
gradle dependency in your project
