### ISSUE TITLE
Upgrade com.android.support dependency

### ISSUE THREAD

**Issue by mariogarcia** [robospock/RoboSpock#41]
Hi:

First of all, congratulations, it's nice to see unit testing with Spock on Android. Good work.

I think the latest android support library is 22.0.1 and even the Android Studio is now complaining saying the 19.x.x is too old to be used. 

Do you have any plans to upgrade the android support dependency any time soon ?

**Comment by pjakubczyk** [comment]
It's not part of Robolectric core. It's a provided dependency. Please check wiki page
https://github.com/robolectric/robolectric/wiki/2.4-to-3.0-Upgrade-Guide#modules

latest jitpack has no dependency to support library
https://jitpack.io/private#robospock/RoboSpock/c9ee6221cd9ac5010bb8c39e110b7e9c272e0a9a

**Comment by pelotasplus** [comment]
rudy forgot to mention that it's true, if you use latest robospock from master.
instead of bumping android support library dependency we decided to bump robolectric to 3.0. cool, right?

**Comment by mariogarcia** [comment]
Nice thanks. I'll check it out.
