### ISSUE TITLE
Add RobolectricGradleTestRunner bits to RoboSputnik

### ISSUE THREAD

**Issue by pelotasplus** [robospock/RoboSpock#46]
With Robolectric 3.0 comes a new [RobolectricGradleTestRunner](http://robolectric.org/javadoc/3.0/org/robolectric/RobolectricGradleTestRunner.html) and we could move bits from it to RoboSputnik so that there is no need to add @Config annotations to all Specs so that AndroidManifest.xml file is visible to Robolectric.

**Comment by pjakubczyk** [comment]
Done in https://github.com/robospock/RoboSpock/tree/0.8.0
