### ISSUE TITLE
"class not found" using com.android.tools.build:gradle:1.5.0

### ISSUE THREAD

**Issue by tehras** [robospock/RoboSpock#57]
This is pretty intermittent, is anyone else running into the same issues?

**Comment by tehras** [comment]
Oops i guess this is the groovy-android-gradle plugin's fault - https://github.com/groovy/groovy-android-gradle-plugin/issues/61

**Comment by pjakubczyk** [comment]
usually compile issues are caused by the groovy plugin.

closing ticket. thx
