### ISSUE TITLE
Error:Class com.android.build.gradle.internal.scope.VariantScopeImpl does not implement the requested interface com.android.build.gradle.internal.scope.BaseScope

### ISSUE THREAD

**Issue by henriquedesousa** [robospock/RoboSpock#61]
If the android gradle plugin is updated to 2.2.0-alpha5, we're start getting the following error while syncing gradle files:

`Error:Class com.android.build.gradle.internal.scope.VariantScopeImpl does not implement the requested interface com.android.build.gradle.internal.scope.BaseScope`

If we comment out the plugin, it will work.

`classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:0.3.10'
apply plugin: 'groovyx.grooid.groovy-android'`

I've gisted a logfile with the corresponding error messages: https://gist.github.com/henriquedesousa/61fe25cb273637eacaaef2fa27532abb

**Comment by pjakubczyk** [comment]
The `groovyx.grooid.groovy-android` is a separate project on which RoboSpock depends.

Please follow releases of groovy plugin by watching this repository https://github.com/groovy/groovy-android-gradle-plugin

Closing as it's not problem of RoboSpock itself.
Thanks for using my library !

**Comment by henriquedesousa** [comment]
Thank you for pointing me in the right direction 👍
