### ISSUE TITLE
Can't run a single spec with gradle?

### ISSUE THREAD

**Issue by walid-halabi-myob** [robospock/RoboSpock#69]
So I've tried ./gradlew -Dtest.single=SomeSpec and it runs all the tests.

I've also tried ./gradlew -DtestSomeVarient=SomeSpec, as well as ./gradlew -Dtest.com.some.package.SomeSpec (and the various combinations of these 2 approaches) and still no 🎲 

Any ideas? I have a feeling I got this working about a year ago but there's no docs that help.

**Comment by Opalo** [comment]
@walid-halabi-myob it should be doable as describe here: https://stackoverflow.com/questions/31344419/gradle-run-only-one-test-suite/31370966#31370966

**Comment by walid-halabi-myob** [comment]
Wow that was fast, thanks for the answer.

I tried this with both gradle 2.8 (what we were using) and gradle 3.3, and both give me:

> Unknown command-line option '--tests'.

Not sure when this command line option was available? I'm thinking it comes in via a plugin, but not sure which?

**Comment by walid-halabi-myob** [comment]
That's odd, I found this, which seems to indicate it should work: https://docs.gradle.org/current/userguide/java_plugin.html#test_filtering

**Comment by walid-halabi-myob** [comment]
Hold up! Looks like the option works if you use testVariant rather than test. Annoying though. Have another issue now, but probably unrelated. Thanks for your help!

**Comment by walid-halabi-myob** [comment]
For anyone coming later, this works: ./gradlew testDebug --tests com.package.ClassOfSpec

Note the use of the variant testDebug. just using the _test_ task fails with the _Unknown command-line option_ error

Also, using the -Dtest.single system property method has been superseded by the test filtering approach (--tests) as above.
