### ISSUE TITLE
Robolectric 3.4.2?

### ISSUE THREAD

**Issue by autonomousapps** [robospock/RoboSpock#70]
Any interest in bumping this? Currently I cannot set SDK to 24.

**Comment by autonomousapps** [comment]
I'm willing to take a stab at this (currently looking at the code), but there are a LOT of breaking changes since Robolectric 3.0, and I'm not familiar at all (yet) with the inner workings of that project.

**Comment by autonomousapps** [comment]
Yay, found a migration guide: http://robolectric.org/migrating/#migrating-from-33-to-34

**Comment by hkhc** [comment]
I make another project based on RoboSpock code, which should be more or less work on Robolectric 3.4

[ElectricSpock](https://github.com/hkhc/electricspock)

**Comment by autonomousapps** [comment]
What about this issue? https://github.com/hkhc/electricspock/issues/3

**Comment by hkhc** [comment]
Just released ElectricSpock 0.6, should be OK with Robolectric 3.4.2.

**Comment by autonomousapps** [comment]
Thank you! I will take a look.

**Comment by autonomousapps** [comment]
Happy to report ElectricSpock currently meets my needs.
