### ISSUE TITLE
Groovy plugin incompatible with android plugin

### ISSUE THREAD

**Issue by frankiesardo** [robospock/RoboSpock#8]
Since the groovy plugin extends from the java plugin, I'm receiving the following error:

> The 'java' plugin has been applied, but it is not compatible with the Android plugins.
> 
> Consult IDE log for more details (Help | Show Log)

I don't know how this can work for you guys

**Comment by pjakubczyk** [comment]
There is plugin 
apply plugin: 'groovyx.grooid.groovy-android'

in
https://github.com/Polidea/RoboSpock/blob/master/sample/build.gradle

which allows to run groovy tests from android project
